// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBxCUaozUfc-Z0UEqeJZmZ3b5GcK14hMM',
    appId: '1:381646202964:web:7985329bf290c86ed0a5c1',
    messagingSenderId: '381646202964',
    projectId: 'quizcraft-b16c7',
    authDomain: 'quizcraft-b16c7.firebaseapp.com',
    storageBucket: 'quizcraft-b16c7.firebasestorage.app',
    measurementId: 'G-GX7CE6NXHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTBUS0KyVPOXai3-euolb-YjKPTASTnY',
    appId: '1:381646202964:android:3ccab1545ae77381d0a5c1',
    messagingSenderId: '381646202964',
    projectId: 'quizcraft-b16c7',
    storageBucket: 'quizcraft-b16c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfGYQYmsrZ1jPijkOyVx1hB7_G3J1eUc',
    appId: '1:381646202964:ios:6fb8e7e94409be68d0a5c1',
    messagingSenderId: '381646202964',
    projectId: 'quizcraft-b16c7',
    storageBucket: 'quizcraft-b16c7.firebasestorage.app',
    iosBundleId: 'com.example.quizcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfGYQYmsrZ1jPijkOyVx1hB7_G3J1eUc',
    appId: '1:381646202964:ios:6fb8e7e94409be68d0a5c1',
    messagingSenderId: '381646202964',
    projectId: 'quizcraft-b16c7',
    storageBucket: 'quizcraft-b16c7.firebasestorage.app',
    iosBundleId: 'com.example.quizcraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBxCUaozUfc-Z0UEqeJZmZ3b5GcK14hMM',
    appId: '1:381646202964:web:0b1f4e10cd76f6b1d0a5c1',
    messagingSenderId: '381646202964',
    projectId: 'quizcraft-b16c7',
    authDomain: 'quizcraft-b16c7.firebaseapp.com',
    storageBucket: 'quizcraft-b16c7.firebasestorage.app',
    measurementId: 'G-FZV9MFVRGN',
  );
}
